pandoc ".\Parte 1.md" --reference-doc=reference.docx -s -o ".\generated\Parte 1.docx" 
pandoc -s ".\Parte 2.md" --reference-doc=reference.docx  -o ".\generated\Parte 2.docx" 
pandoc -s ".\Parte 3.md" --reference-doc=reference.docx  -V fontsize=13pt -o ".\generated\Parte 3.docx" 
pandoc -s ".\todo.md" --reference-doc=reference.docx -o ".\generated\todo.docx" 
pandoc -s ".\README.md" --reference-doc=reference.docx  -o ".\generated\README.docx" 
pandoc -s ".\Ale.md" --reference-doc=reference.docx -o ".\generated\Ale.docx" 
pandoc -s ".\help.md" --reference-doc=reference.docx -o ".\generated\help.docx"
